services:
  web:
    build: .
    command: "tail -f /dev/null"
    volumes:
      - ..:/app
    ports:
      - 8000:8000
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgresql://postgres:postgres@db:5432/campaign_system

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_DB=campaign_system
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres

# volumes:
#   postgres_data:
